# Generated by Django 4.0.4 on 2022-06-07 16:00

import apifitnes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apifitnes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpersonal',
            name='age',
            field=models.IntegerField(validators=[apifitnes.models.validateage], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='age',
            field=models.IntegerField(validators=[apifitnes.models.validateage], verbose_name='Возраст'),
        ),
    ]
